platform :ios do
  desc "Deploy ios app on the appstore"

  lane :metadata do
    appstore(
      skip_binary_upload: true
    )
  end

  lane :deploy do
    match(
      type: "appstore",
      git_url: "git@gitlab.cozycloud.cc:labs/mobile-certificates.git"
    )
    cordova(platform: 'ios')
    appstore(ipa: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'])
  end
end

platform :android do
  desc "Deploy android app on play store"

  lane :metadata do
    supply(skip_upload_apk: true)
  end

  lane :deploy do
    supply(
      apk: './build/android/cozy-banks.apk',
      track: 'beta',
      skip_upload_screenshots: true,
      skip_upload_images: true
    )
  end
end
