#!/bin/bash

# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -euo pipefail

JOB_UPDATE_RECETTE="ad27f2f6-63d9-4a16-ab62-e25c957875b5"
JOB_UPDATE_STAGING="ad27f2f6-63d9-4a16-ab62-e25c957875b5"
function executeRundeck {
  INSTANCE=$1
  JOB=$2
  APP_SLUG=$3
  curl --fail -X POST -H "X-Rundeck-Auth-Token: $RUNDECK_TOKEN" https://rundeck.cozycloud.cc/api/20/job/$JOB/run?argString=-instance+$INSTANCE+-slugs+$APP_SLUG

  echo ""
}

function sendMattermostMsg {
  INSTANCE=$1
  MATTERMOST_ICON="https://travis-ci.com/images/logos/TravisCI-Mascot-1.png"
  MATTERMOST_USERNAME="Travis"
  MATTERMOST_CHANNEL="Gangsters-release"

  GIT_LOG=$(git log -1 "--pretty=format:%h %s")
  MATTERMOST_TEXT="$INSTANCE updated for $APP_SLUG. [$GIT_LOG](https://github.com/$TRAVIS_REPO_SLUG/commit/$TRAVIS_COMMIT)."

  curl -X POST -d "payload=\
      {\"channel\":\"${MATTERMOST_CHANNEL}\",\
       \"icon_url\": \"${MATTERMOST_ICON}\",\
       \"username\": \"${MATTERMOST_USERNAME}\", \
       \"text\": \"${MATTERMOST_TEXT}\"}" ${MATTERMOST_HOOK_URL}

  echo ""
}

function deploy {
  INSTANCE=$1
  JOB=$2
  APP_SLUG=$3

  executeRundeck $INSTANCE $JOB $APP_SLUG
  sendMattermostMsg $INSTANCE

  sleep 5 # Cannot have the same rundeck job running twice
}

echo "Deploying built code on GitHub:"
yarn deploy

if [ DEPLOY_BRANCH == 'latest' ]; then
  APP_SLUG="banks"

  echo "Deploying on gangsters:"
  deploy "gangsters" $JOB_UPDATE_STAGING $APP_SLUG
else
  APP_SLUG="banks"

  echo "Deploying on recette:"
  deploy "recette" $JOB_UPDATE_RECETTE $APP_SLUG

  echo "Deploying on grrecette:"
  deploy "grrecette" $JOB_UPDATE_RECETTE $APP_SLUG
fi
