#!/bin/bash

# https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -euo pipefail

APP_SLUG="banks"

function executeRundeck {
  INSTANCE=$1
  JOB=$2
  curl --fail -X POST -H "X-Rundeck-Auth-Token: $RUNDECK_TOKEN" https://rundeck.cozycloud.cc/api/20/job/$JOB/run?argString=-instance+$INSTANCE+-slugs+$APP_SLUG

  echo ""
}

function sendMattermostMsg {
  INSTANCE=$1
  MATTERMOST_ICON="https://travis-ci.com/images/logos/TravisCI-Mascot-1.png"
  MATTERMOST_USERNAME="Travis"
  MATTERMOST_CHANNEL="Gangsters-release"

  GIT_LOG=$(git log -1 "--pretty=format:%h %s")
  MATTERMOST_TEXT="$INSTANCE updated for $APP_SLUG. [$GIT_LOG](https://github.com/$TRAVIS_REPO_SLUG/commit/$TRAVIS_COMMIT)."

  curl -X POST -d "payload=\
      {\"channel\":\"${MATTERMOST_CHANNEL}\",\
       \"icon_url\": \"${MATTERMOST_ICON}\",\
       \"username\": \"${MATTERMOST_USERNAME}\", \
       \"text\": \"${MATTERMOST_TEXT}\"}" ${MATTERMOST_HOOK_URL}

  echo ""
}

function deploy {
  INSTANCE=$1
  JOB=$2

  executeRundeck $INSTANCE $JOB
  sendMattermostMsg $INSTANCE

  sleep 5 # Cannot have the same rundeck job running twice
}

echo "Deploying built code on GitHub:"
yarn deploy

if [ DEPLOY_BRANCH == 'latest' ]; then
  JOB="ad27f2f6-63d9-4a16-ab62-e25c957875b5"

  echo "Deploying on gangsters:"
  deploy "gangsters" $JOB
else
  JOB="87a668f7-eff1-422d-aa84-92b3bcc62c8f"

  echo "Deploying on recette:"
  deploy "recette" $JOB

  echo "Deploying on grrecette:"
  deploy "grrecette" $JOB
fi
