name: CI/CD

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'

env:
  MATTERMOST_CHANNEL: '{"dev":"gangsters","beta":"gangsters,publication","stable":"gangsters,publication"}'
  MATTERMOST_HOOK_URL: ${{ secrets.MATTERMOST_HOOK_URL }}
  REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint & Quality checks
        run: |
          yarn lint
          yarn check-locales
          yarn check-fixtures
      - name: Test
        run: yarn test --runInBand
      - name: Build
        run: yarn build
      - name: BundleMon
        uses: lironer/bundlemon-action@v1
      - name: Set SSH for downcloud
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DOWNCLOUD_SSH_KEY }}
      - name: Publish
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        run: |
          yarn run cozyPublish --yes
          yarn uploadStaticFiles
